// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vezeeta.Models
{
    public partial class Appointment
    {
        [Column(TypeName = "datetime")]
        public DateTime? start_date { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? end_date { get; set; }
        public int? patients_per_day { get; set; }
        public bool? type { get; set; }
        [Key]
        public int Dr_id { get; set; }
        [Key]
        public int id { get; set; }
        public int? appoint_id { get; set; }

        [ForeignKey("Dr_id")]
        [InverseProperty("Appointments")]
        public virtual Doctor Dr { get; set; }
        [ForeignKey("appoint_id")]
        [InverseProperty("Appointments")]
        public virtual Patient_Appoinment appoint { get; set; }
    }
}