// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vezeeta.Models
{
    public partial class City
    {
        public City()
        {
            Addresses = new HashSet<Address>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [StringLength(50)]
        public string status { get; set; }
        public int region_id { get; set; }

        [ForeignKey("region_id")]
        [InverseProperty("Cities")]
        public virtual Region region { get; set; }
        [InverseProperty("city")]
        public virtual ICollection<Address> Addresses { get; set; }
    }
}