// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vezeeta.Models
{
    [Table("Clinic_Doctor")]
    public partial class Clinic_Doctor
    {
        [Key]
        public int Dr_id { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? fees { get; set; }
        [Key]
        public int clinic_id { get; set; }

        [ForeignKey("Dr_id")]
        [InverseProperty("Clinic_Doctors")]
        public virtual Doctor Dr { get; set; }
        [ForeignKey("clinic_id")]
        [InverseProperty("Clinic_Doctors")]
        public virtual Clinic clinic { get; set; }
    }
}