// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vezeeta.Models
{
    [Index("phone", Name = "phone_unique", IsUnique = true)]
    public partial class Clinic
    {
        public Clinic()
        {
            Clinic_Doctors = new HashSet<Clinic_Doctor>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [Required]
        [StringLength(12)]
        public string phone { get; set; }

        [InverseProperty("clinic")]
        public virtual Address Address { get; set; }
        [InverseProperty("clinic")]
        public virtual ICollection<Clinic_Doctor> Clinic_Doctors { get; set; }
    }
}