// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vezeeta.Models
{
    public partial class Doctors_Phone
    {
        [Key]
        [StringLength(12)]
        public string phone { get; set; }
        [Key]
        public int Dr_id { get; set; }

        [ForeignKey("Dr_id")]
        [InverseProperty("Doctors_Phones")]
        public virtual Doctor Dr { get; set; }
    }
}