// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vezeeta.Models
{
    public partial class Prescription
    {
        [Key]
        public int Dr_id { get; set; }
        [Key]
        public int patient_id { get; set; }
        [Required]
        [StringLength(150)]
        public string medicine { get; set; }
        public string description { get; set; }

        [ForeignKey("Dr_id")]
        [InverseProperty("Prescriptions")]
        public virtual Doctor Dr { get; set; }
        [ForeignKey("patient_id")]
        [InverseProperty("Prescriptions")]
        public virtual Patient patient { get; set; }
    }
}