// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vezeeta.Models
{
    public partial class Question
    {
        public Question()
        {
            Answers = new HashSet<Answer>();
        }

        [Key]
        public int id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? create_at { get; set; }
        [Required]
        public string description { get; set; }
        [Required]
        [StringLength(100)]
        public string title { get; set; }
        public int age { get; set; }
        [StringLength(1)]
        public string gender { get; set; }
        public int spec_id { get; set; }
        public int? patient_id { get; set; }
        [StringLength(50)]
        public string type { get; set; }

        [ForeignKey("patient_id")]
        [InverseProperty("Questions")]
        public virtual Patient patient { get; set; }
        [ForeignKey("spec_id")]
        [InverseProperty("Questions")]
        public virtual Specialization spec { get; set; }
        [InverseProperty("Q_idNavigation")]
        public virtual ICollection<Answer> Answers { get; set; }
    }
}