// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vezeeta.Models
{
    public partial class Review
    {
        [Key]
        public int Dr_id { get; set; }
        [Key]
        public int patient_id { get; set; }
        [Required]
        public string value { get; set; }
        [StringLength(150)]
        public string comment { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? created_at { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? updated_at { get; set; }

        [ForeignKey("Dr_id")]
        [InverseProperty("Reviews")]
        public virtual Doctor Dr { get; set; }
        [ForeignKey("patient_id")]
        [InverseProperty("Reviews")]
        public virtual Patient patient { get; set; }
    }
}