// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vezeeta.Models
{
    public partial class Specialization
    {
        public Specialization()
        {
            Doctors = new HashSet<Doctor>();
            Questions = new HashSet<Question>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(100)]
        public string name { get; set; }
        [StringLength(250)]
        public string image { get; set; }

        [InverseProperty("id_specializeNavigation")]
        public virtual ICollection<Doctor> Doctors { get; set; }
        [InverseProperty("spec")]
        public virtual ICollection<Question> Questions { get; set; }
    }
}